name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install Bitcoin Kernel Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential cmake pkgconf python3 libevent-dev libboost-dev capnproto libcapnp-dev
      - name: Format Check
        run: |
          cargo fmt -- --check
          cargo clippy --all-targets -- -D warnings
          cargo check --all-features
      - name: MSRV
        run: |
          cargo install cargo-msrv@0.19.2
          cargo msrv verify
      - name: Test
        run: cargo test --workspace --all-features

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install Bitcoin Kernel Dependencies
        run: brew install cmake pkgconf libevent boost capnp
      - name: Check
        run: cargo check --all-features
      - name: Test
        run: cargo test --workspace --all-features
